name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or main

permissions:
  contents: write
  deployments: write
  issues: write
  pull-requests: write
  statuses: write
  checks: write
  discussions: write
  packages: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js (optional, remove if unused)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # This assumes index.html is at the root